
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  username text,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, first_name, last_name, username)
  values (
    new.id,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name',
    new.raw_user_meta_data ->> 'username'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.farm_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  location text not null,
  farm_size numeric(10,2),
  crop text not null,
  plant_growth_stage text,
  activity_type text not null,
  condition_of_irrigation_system text,
  irrigating boolean not null default false,
  description text,
  fertilizer_used text,
  crop_condition text,
  pest_observations text,
  pest_control_measures text,
  created_at timestamptz not null default now()
);

create table if not exists public.irrigation_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_name text not null,
  location text not null,
  farm_size numeric(10,2),
  crop_type text not null,
  plant_growth_stage text,
  irrigation_method text not null,
  irrigation_duration numeric(10,2),
  water_amount numeric(14,2),
  water_source text,
  pump_used boolean not null default false,
  fertilizer_used text,
  filter_type text,
  soil_type text,
  weather_conditions text,
  leakage boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.maintenance_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  equipment_name text not null,
  maintenance_type text not null,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  problem_type text not null,
  description text not null,
  contact_info text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.farm_activities enable row level security;
alter table public.irrigation_logs enable row level security;
alter table public.maintenance_requests enable row level security;
alter table public.reports enable row level security;

drop policy if exists "Users manage their profile" on public.profiles;
create policy "Users manage their profile"
  on public.profiles for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users manage their farm activities" on public.farm_activities;
create policy "Users manage their farm activities"
  on public.farm_activities for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage their irrigation logs" on public.irrigation_logs;
create policy "Users manage their irrigation logs"
  on public.irrigation_logs for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage their maintenance requests" on public.maintenance_requests;
create policy "Users manage their maintenance requests"
  on public.maintenance_requests for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage their reports" on public.reports;
create policy "Users manage their reports"
  on public.reports for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists farm_activities_user_created_idx
  on public.farm_activities (user_id, created_at desc);
create index if not exists irrigation_logs_user_created_idx
  on public.irrigation_logs (user_id, created_at desc);
create index if not exists maintenance_requests_user_created_idx
  on public.maintenance_requests (user_id, created_at desc);
create index if not exists reports_user_created_idx
  on public.reports (user_id, created_at desc);
