# Generated by Django 6.0.4 on 2026-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Irrigation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=255)),
                ("water_amount", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
