# Generated by Django 6.0.4 on 2026-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_farm_crop"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="condition_of_irrigation_system",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="farm",
            name="farm_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="farm",
            name="location",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="farm",
            name="pest_control_measures",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AddField(
            model_name="farm",
            name="pest_observations",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AddField(
            model_name="farm",
            name="plant_growth_stage",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="crop_type",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="farm_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="irrigation_duration",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="irrigation_method",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="location",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="plant_growth_stage",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="soil_type",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="weather_conditions",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
